<?php

return [
    'wordsBlocks' => [
        'crear',
        'poema',
        'hackear',
        'crackear',
        'piratear',
        'descargar',
        'torrent',
        'warez',
        'fuga',
        'filtración',
        'leak',
        'phishing',
        'exploit',
        'virus',
        'malware',
        'ransomware',
        'ataque',
        'infectar',
        'ddos',
        'botnet',
        'troyano',
        'rootkit',
        'keylogger',
        'scam',
        'estafa',
        'suplantación',
        'desnudo',
        'pornografía',
        'sexo',
        'drogas',
        'armas',
        'violencia',
        'acoso',
        'discriminación',
        'racismo',
        'xenofobia',
        'homofobia',
        'incitación',
        'odio',
        'extremismo',
    ],
    "auth" => true,
    "sensitivity" => 70,
    "methods"=> [
            [
                "method"=> "GetFunctions",
                "mensajes"=>[
                    "Que funcionalidades tienes?",
                    "muestrame que puedes hacer",
                    "muestrame tus funcionalidades",
                    "dime que peudes hacer",
                    "que funcionalidades tienes programadas?"
                ]
            ],
            [
                "method"=> "UpdatePassword",
                "mensajes"=>[
                    "Ayudame a actualizar mi contraseña",
                    "podrias actualizar mi contraseña",
                    "actualiza mi contraseña por favor",
                    "actualiza mi contraseña a esta",
                    "modifica mi contraseña de usuario",
                    "actualiza mi contraseña de usuario",
                    "ayudame a modificar mi contraseña registrada",
                ]
            ],
            [
                "method"=> "UpdateEmail",
                "mensajes"=>[
                    "Actualizar mi correo",
                    "podrias actualizar mi correo",
                    "modifica mi correo de usuario",
                    "actualiza mi correo de usuario",
                    "ayudame a modificar mi correo registrado",
                    "actualiza mi correo registrado",
                    "podrias actualizar mi correo registrado",
                    "modifica mi correo registrado",
                ]
            ],
            [
                "method"=> "DataEmployees",
                "mensajes"=>[
                    "Cuantos empleados hay en la empresa?",
                    "podrias listar los empleados de la empresa por su",
                    "lista a los empleados por su",
                    "muestrame a los empleados cuyo nombre sea",
                    "quien es el empleado con el nombre",
                    "quien es el empleado",
                    "Cual es el numero de celular del empleado",
                    "muestrame el telefono de",
                    "podrias darme el telefono de",
                    "cual es el telefono de",
                    "cual es el correo de",
                    "cual es el correo del empleado",
                    "muestrame el correo de",
                    "muestrame la informacion de",
                    "listame la informacion de",
                    "muestrame todos los datos de",
                    "muestrame todos los datos del empleado",
                    "dame la informacion de",
                    "muesta el numero de celular de",
                    "muestrame el celular del empleado",
                    "muestrame el numero de celular del empleado",
                    "cual es el direccion de",
                    "cual es la direccion del empleado",
                    "cual es la identificacion del empleado",
                    "cual es el numero de cedula del empleado",
                    "cual es el numero de cedula de",
                    "cual es el numero de identificacion de",
                    "cual es la fecha de cumpleaños de",
                    "en que fecha ingreso el empleado",
                    "en que fecha ingreso",
                    "cual fue la fecha de ingreso del empleado",
                    "cual es la fecha de ingreso de",
                    "recuerdas en que fecha ingreso el empleado",
                    "recuerdas en que fecha ingreso",
                    "muestrame al empleado que tenga el celular",
                    "podrías mostrame todo los empleados cuyo nombre empiece por la letra",
                    "podrías mostrame todo los empleados cuyo nombre empiece por la",
                    "hay un empleado que se llame xxxx en el sistema",
                    "muestrame los datos de la empleada",
                    "muestrame una lista de los nombres de todos los empleados"
                ]
            ],
            [
                "method"=> "RegisterEmployee",
                "mensajes"=>[
                    "podrias registrar un empleado",
                    "quiero registrar un nuevo empleado",
                    "podrias registrar un nuevo empleado",
                    "ayudame a crear el registro de un nuevo empleado",
                    "podrias crear el registro de un nuevo empleado",
                    "me gustaria crear el registro de un nuevo empleado",
                    "registremos un nuevo empleado",
                    "registra un nuevo empleado",
                    "ayudame a registrar un nuevo empleado",
                ]
            ],
            [
                "method"=> "UpdateEmployee",
                "mensajes"=>[
                    "podrias actualizar los datos del empleado",
                    "quiero actualizar los datos del empleado",
                    "podrias actualizar los datos de",
                    "ayudame a actualizar los datos de",
                    "quisiera actualizar los datos de",
                    "actualiza los datos de",
                    "actualicemos los datos de",
                    "actualiza los datos del empleado",
                    "quiero actualizar los datos del empleado",
                    "quiero actualizar los datos de",
                    "actualicemos los datos del empleado",
                    "cambiemos el correo del empleado",
                    "cambiemos el telefono del empleado",
                    "cambiemos el nombre del empleado",
                    "cambiemos la direccion del empleado",
                    "cambiemos la identificacion del empleado",
                    "cambiemos el numero de identificacion del empleado",
                    "cambiemos el numero de cedula del empleado",
                    "cambiemos el numero de celular del empleado",
                    "cambiemos el nombre del empleado",
                    "cambiemos el nombre de",
                    "cambiemos el correo de",
                    "cambiemos el telefono de",
                    "cambiemos la direccion de",
                    "cambiemos la identificacion de",
                    "cambiemos el numero de identificacion de",
                    "cambiemos el numero de cedula de",
                    "cambiemos el numero de celular de",
                    "cambiemos el nombre del empleado",
                ]
            ]



]
];
